baseURL = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Daniel Ray"
title = "Daniel Ray's Blog"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
disqusShortname = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["hugo","vitae","theme","static"]

	# Add meta description in head part
	description = "Vitae is a blog theme for Hugo that focuses on your content."

	# Add pagetitle to homepage <title> tag
	pagetitle = "All about static site generation"

	# Add a subtitle to your website
	subtitle = "Computer science and programming"

	# Activate to show authors on pages if available
	#listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	# Custom CSS applied to default styles.
	customCSS = "css/custom.css"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/jdanray"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/daniel-ray-055616129/"
